// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID            int32        `json:"id"`
	Name          string       `json:"name"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	Url           string       `json:"url"`
	UserID        int32        `json:"user_id"`
	LastFetchedAt sql.NullTime `json:"last_fetched_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Counter   int32     `json:"counter"`
}
