// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at, counter
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Counter,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, created_at, updated_at, counter FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Counter,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, updated_at = $3
WHERE id = $1
RETURNING id, name, created_at, updated_at, counter
`

type UpdateUserParams struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.Name, arg.UpdatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Counter,
	)
	return i, err
}

const updateUserCounter = `-- name: UpdateUserCounter :exec
UPDATE users
SET counter = $2, updated_at = $3
WHERE id = $1
`

type UpdateUserCounterParams struct {
	ID        int32     `json:"id"`
	Counter   int32     `json:"counter"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUserCounter(ctx context.Context, arg UpdateUserCounterParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCounter, arg.ID, arg.Counter, arg.UpdatedAt)
	return err
}
